version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      day: tuesday
      time: "09:00"
      timezone: America/New_York
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: America/New_York
    open-pull-requests-limit: 5
