name: Release Drafter
on:
  push:
    branches: [$default-branch]

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
    - uses: release-drafter/release-drafter@v5.11.0
      with:
        config-name: release_drafter.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
